Refactor bayesian eoq to be OOP
supplyseer-ai/supplyseer pull request #47
Opened 2024-12-20 15:33 UTC by yusufprasetyo25

This commit introduces refactor code of bayesian EOQ to be OOP with NumPy style.
The key updates include:

- Introduces `BayesianEOQ` class which encapsulates all previous computation
- Introduces `BayesianDistribution` class for parameters to generate probability distribution of `demand`, `order_cost`, and `holding_cost`
- Introduces `SimulationParameters` class for parameters related to the simulation, such as `parameter_grid`, etc.
- Ensures backward compatibility to old `bayesian_eoq_full()` function
- Fixes max and min EOQ to use min and max holding cost respectively since it is in denominator
- Adjusts test accordingly

References
- This commit was made in response to #21  
- This commit was build on #22

2025-01-28 09:01 UTC, jakorostami reviewed
test comment

2025-01-28 09:01 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +@dataclass
Good job separating concerns. You think we can use Pydantic V2 instead of dataclass?

2025-01-28 09:01 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +    @staticmethod
Why static decorator for a method that takes varying arguments?

2025-01-28 09:01 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +@dataclass
pydantic

2025-01-28 09:01 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +    def _calculate_credible_quantile(self) -> List[float]:
naming convention: credible interval

2025-01-28 09:01 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +class BayesianDistribution:
naming convention: it is not a _Bayesian_ distribution. Think we can rename?

2025-02-03 02:46 UTC, yusufprasetyo25 commented on supplyseer/bayesian/bayesian_eoq.py
> +@dataclass
Hi Jako, thank you for the input. Yes, we can. I will change to Pydantic V2

2025-02-03 02:57 UTC, yusufprasetyo25 commented on supplyseer/bayesian/bayesian_eoq.py
> +    @staticmethod
Thank you for this feedback. As far as I know, static method should be used when our method doesn't use self related arguments, which is applicable to this particular method.

I want to make sure I fully understand your suggestion. Could you please provide an example to clarify your expectation for this part? Thanks!

2025-02-03 03:00 UTC, yusufprasetyo25 commented on supplyseer/bayesian/bayesian_eoq.py
> +class BayesianDistribution:
Oh, you're right! Will change it to a more general ProbabilityDistribution class to anticipate possible future additions. Thanks

2025-02-03 19:22 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +    @staticmethod
Good point!

2025-02-03 19:24 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +class BayesianDistribution:
Fix the needed stuff and let me know. We'll do some tests and then merge to develop.

2025-02-13 14:46 UTC, yusufprasetyo25 commented
Hi @jakorostami. Sorry for the late revision. Please help me to review it. Thank you!

2025-02-19 18:06 UTC, jakorostami requested changes
please separate data models and behaviour and resolve the comments

2025-02-19 18:06 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +class ProbabilityDistribution(BaseModel):
No behaviour in pydantic models

2025-02-19 18:06 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +class SimulationParameters(BaseModel):
This is aligned with the design pattern for supplyseer

2025-02-19 18:06 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +class BayesianEOQ(BaseModel):
No behaviour in pydantic models

2025-02-19 18:06 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +    def normal_pdf(x: np.ndarray, mean: float, std: float) -> np.ndarray:
Can be a standalone if you want but no behaviour in pydantic models

2025-02-19 18:06 UTC, jakorostami commented on supplyseer/bayesian/bayesian_eoq.py
> +def bayesian_eoq_full(d: float, a: float, h: float,
this is not needed if we have built a module for the bayesian eoq

2025-03-01 14:56 UTC, jakorostami commented
Can you write docs of the functionality, what it is intended to do and why?

Also please add a notebook demonstrating it.

No LLM please, thanks.

2025-03-11 01:01 UTC, yusufprasetyo25 commented
I'm working on it. Thank you for the review

2025-10-08 17:38 UTC, jakorostami commented
No activity, closing this

2025-10-08 17:38 UTC, closed without merging

2025-10-10 01:03 UTC, yusufprasetyo25 commented
Hi Jako, I tried to modify the readme and created example notebook in the last commit [here](https://github.com/supplyseer-ai/supplyseer/pull/47/commits/1148acbe0729b741075f4b90fee89a226e5dd91d)

Would you please check it again before closing the thread? Thanks